### ISSUE TITLE
Add option to translate ~ to the User directory for the current user (wslpath)

### ISSUE THREAD

**Issue by JacobDB** [darealshinji/scripts#2]
https://github.com/darealshinji/scripts/blob/master/wslpath

For example, I have a symlink set up a `~/Downloads` which maps to `/mnt/c/Users/Jacob/Downloads` (`C:\Users\Jacob\Downloads` in Windows), but running `wslpath -w ~/Downloads` incorrectly reports `\lxss\home\jacob\Downloads`. It'd be very useful to add a flag that translates `~` to the corresponding User's folder on Windows.

**Comment by JacobDB** [comment]
Here's a link to how I was doing this myself with a custom `winpath` script (I've since switched to using `wslpath`, as it's much better).

https://gist.github.com/JacobDB/e71e22c3663175b2369211aeb54362fe#file-winpath-sh-L8-L19

**Comment by darealshinji** [comment]
It seems `~` is automatically translated to the Unix home path by the current shell. So you want `~` to always point to the Windows "home" path?

Changing the environment variable `HOME` seems to do the trick:
```
$ echo ~
/home/djcj

$ echo $HOME
/home/djcj

$ HOME=/mnt/c/Users/djcj

$ echo $HOME
/mnt/c/Users/djcj

$ echo ~
/mnt/c/Users/djcj
```
I don't know however if that's a feature I'd like to have enabled by default. Enabling this through a command line option or making is possible to switch it on and off by setting a variable at the top of the script may be a better solution. Right now I haven't booted Windows, so I will later take a closer look at it.

**Comment by JacobDB** [comment]
Yea, I was thinking putting it behind a flag or something would be the best method to do this, since `~` is a pretty fundamental thing in Unix. I can just add the flag to my alias functions to make it seamless for my use case.

**Comment by darealshinji** [comment]
I've updated the script. The options `-s` or `--subst-home` will replace the Unix home path with the Windows user path:
```
$ wslpath -w ~/"New Folder"
C:\Users\djcj\AppData\Local\lxss\home\djcj\New Folder

$ wslpath -w -s ~/"New Folder"
C:\Users\djcj\New Folder
```

**Comment by JacobDB** [comment]
Hmm, doesn't seem to be working for me, here's my output:

    jacob@SURFACE-LAPTOP:~$ wslpath -w -s ~/Downloads
    w\lxss\mnt\\Downloads
    jacob@SURFACE-LAPTOP:~$ wslpath -w ~/Downloads
    w\lxss\home\jacob\Downloads
    jacob@SURFACE-LAPTOP:~$ wslpath -w /mnt/c/Users/Jacob/Downloads
    C:\Users\Jacob\Downloads

Am I doing something wrong here? I've tried it with quotes around the folder name too, and it's still acting weird.

**Comment by JacobDB** [comment]
Ah, I see, I needed to add `-r` to resolve the symlinks. Now I'm having a small issue with my alias functions, but that's my issue to deal with :) Thanks much!
