### ISSUE TITLE
Script doesn't resolve symlinks

### ISSUE THREAD

**Issue by laurent22** [darealshinji/scripts#3]
I've got some files in /var/www/web, which is a symlink /mnt/d/www/web (D:\www\web) and for this path, if I run `wslpath -w /var/www/web` I get:

    C:\Users\Laurent\AppData\Local\lxss\rootfs\var\www\web

So it seems it assumes that all root paths are under lxss, which is not always true.

I think it's possible to fix this using the output of cmd.exe `cd`. For example, if I type this in Bash from /var/www/web:

    cmd.exe /c cd

It will correctly resolve the symlink and print the path:

    D:\www\web

So I think just using the output of this command it should work.

**Comment by darealshinji** [comment]
The directory `/var` is still under lxss, right? Does it work if you use `-r` to resolve symlinks? (`wslpath -w -r /var/www/web`)

**Comment by darealshinji** [comment]
Are you still having issues with the script?

**Comment by laurent22** [comment]
Hello, sorry I don't know as I no longer use this particular script. I ended up making my own based on `cmd.exe /c cd`.
