### ISSUE TITLE
Working on OpenSUSE

### ISSUE THREAD

**Issue by AltarBeastiful** [darealshinji/scripts#5]
Just tested wslpath on OpenSuse WSL, seems to work mighty fine. 

Could you elaborate the reason for checking the WSL it runs into ?
https://github.com/darealshinji/scripts/blob/cb745f59c0a521f5c9bf0db8b9be5806e6ab1e96/wslpath#L81

**Comment by darealshinji** [comment]
I don't remember why. This script is deprecated anyway, so I might delete it.
